name: CI Build Kernel (ARM)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    
    env:
      KERNEL_TAG: "v6.1"
      DEFCONFIG: multi_v7_defconfig
      CROSS_COMPILE: arm-linux-gnueabihf-

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t lab5-kernel:latest .

      - name: Run Kernel Build inside Container
        run: |
          docker run --rm \
            -u $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/work \
            -w /work \
            lab5-kernel:latest \
            bash -c " \
              export KERNEL_TAG='${{ env.KERNEL_TAG }}'; \
              export DEFCONFIG='${{ env.DEFCONFIG }}'; \
              export CROSS_COMPILE='${{ env.CROSS_COMPILE }}'; \
              ./build_kernel.sh"

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-artifacts
          path: |
            linux/arch/arm/boot/zImage
            linux/arch/arm/boot/dts
          retention-days: 7

      - name: Download Kernel Artifacts
        uses: actions/download-artifact@v4
        with:
          name: kernel-artifacts
          path: ./artifacts

      - name: Install QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-system-arm

      - name: Run QEMU to boot kernel
        run: |
          KIMG=./artifacts/linux/arch/arm/boot/zImage
          DTB=./artifacts/linux/arch/arm/boot/dts/vexpress-v2p-ca9.dtb
          
          echo "Starting QEMU test..."
          qemu-system-arm -M versatilepb -m 256M -nographic \
            -kernel "$KIMG" -dtb "$DTB" \
            -append "console=ttyAMA0 root=/dev/ram rdinit=/init" \
            -no-reboot -serial mon:stdio &
          
          sleep 30
          
          sudo pkill -f qemu-system-arm || true
